apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bundles.cnab.io
spec:
  group: cnab.io
  names:
    kind: Bundle
    listKind: BundleList
    plural: bundles
    singular: bundle
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            name:
              description: Name of the bundle
              type: string
            url:
              description: URL of the bundle in a remote OCI registry
              type: string
          type: object
        status:
          properties:
            processed:
              description: Processed indicates the controller successfully processed
                the pulled bundle
              type: boolean
            pulled:
              description: Pulled indicates the controller successfully pulled the
                bundle from the registry
              type: boolean
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
